# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sidemon < Formula
  desc "Minimal drop-in monitoring for side projects — uptime, errors, traffic, alerts."
  homepage "https://github.com/WHITELOTUS0/sidemon"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WHITELOTUS0/sidemon/releases/download/v0.1.0/sidemon_darwin_amd64.tar.gz"
      sha256 "4593c962b09126e59e67a6c35a4a55a9a6d32933c6bda38864ebae4d69e9137c"

      define_method(:install) do
        bin.install "sidemon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WHITELOTUS0/sidemon/releases/download/v0.1.0/sidemon_darwin_arm64.tar.gz"
      sha256 "e39da638547142b2e612d98248405241dc19b0e1267a5fb4b6e20e6fde213e69"

      define_method(:install) do
        bin.install "sidemon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WHITELOTUS0/sidemon/releases/download/v0.1.0/sidemon_linux_amd64.tar.gz"
      sha256 "ddc5ad8b0b3a074af56ce44918c177fb1f9816c844c5e432fd2f4f038b999cf4"
      define_method(:install) do
        bin.install "sidemon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WHITELOTUS0/sidemon/releases/download/v0.1.0/sidemon_linux_arm64.tar.gz"
      sha256 "794ce633704ce206df82c047127a723d1f728d4b7a23419e8669c14193ae91c0"
      define_method(:install) do
        bin.install "sidemon"
      end
    end
  end

  test do
    system "#{bin}/sidemon", "--help"
  end
end
